# Site settings
title: 孟德的博客
SEOTitle: 孟德佳的博客 | Dejia Blog
header-img: img/home-bg.jpg
email: mengdejia2014@gmail.com
description: "关于后端、体育和金融，还有一些随笔 | Dejia Meng，Software Engineer，Investor and investor | 这里是 @孟德佳 的个人博客，记录技术与生活。"
keyword: "孟德佳, 孟德, Dejia Meng, 孟德佳的博客, Dejia Blog, 博客, 个人网站, 互联网, Web, 架构, 后端"
url: "http://mengdejia.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     dfgsdgdgfdluanxu
zhihu_username:     sdfasfdsafsafsaf
github_username:    dejia2017
twitter_username:   mengdejia
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: mengdejia

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: mengdejia.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "你灵魂的欲望，是你命运的先知"
sidebar-avatar: /img/avatar-mengdejia.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    }
]
